<?php

namespace App\Models;

use App\Models\Admin\OnlineExam\QuestionOptionField;
use App\Models\Admin\Users\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use PHPUnit\Util\Test;
use App\Models\QuestionBank;
use function Laravel\Prompts\select;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'test_type_id',
        'name'
    ];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            $model->created_by = Auth::id();
            $model->updated_at = null;
        });
        self::updating(function ($model){
            $model->updated_by = Auth::id();
        });
        self::deleting(function ($model){
            $model->deleted_by = Auth::id();
            $model->save();
        });
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class,'created_by');
    }

    public function updatedBy()
    {
        return $this->belongsTo(User::class,'updated_by');
    }

    public function deletedBy()
    {
        return $this->belongsTo(User::class,'deleted_by');
    }

    public function testType():BelongsTo
    {
        return $this->belongsTo(TestType::class,'test_type_id');
    }

    public function sub_category()
    {
        return $this->hasMany(SubCategory::class,'category_id');
    }

    public function questions()
    {
        return $this->hasMany(QuestionBank::class,'category_id');
    }

    public function questionsExist()
    {
        return $this->questions()->exists();  // Checks if there are any related questions
    }

    public function fields()
    {
        return $this->hasOne(QuestionOptionField::class,'category_id');
    }

    public function nextSubcategoryWithQuestions($usedSubcategories, $difficulty = 'Medium')
    {
        return $this->sub_category()
            ->whereNotIn('id', $usedSubcategories) // Exclude used subcategories
            ->whereHas('questions', function ($query) use ($difficulty) {
                $query->whereHas('questionLevel', function ($levelQuery) use ($difficulty) {
                    $levelQuery->where('name', $difficulty); // Filter by difficulty
                });
            })
            ->first();
    }

}
