<?php

namespace App\Models;

use App\Models\Admin\Users\User;
use App\Models\Test\Category;
use App\Models\User\SubmittedTest;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Quiz extends Model
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->created_by = Auth::id();
        });

        self::updating(function ($model) {
            $model->updated_by = Auth::id();
        });
        self::deleting(function ($model) {
            $model->deleted_by = Auth::id();
            $model->save();
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function candidateQuiz()
    {
        return $this->hasMany(SubmittedTest::class,'quiz_id');
    }

    public function candidates()
    {
        return $this->hasMany(UserTestEnrollment::class,'quiz_id');
    }

    
    
    public function createdBy()
    {
        return $this->belongsTo(User::class,'created_by');
    }
}
